//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

func main() {
	cwd, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	templatePath := filepath.Clean(filepath.Join(cwd, "../../../resources/templates/ctxpm-managed-entrypoint.md"))
	outputPath := filepath.Join(cwd, "zz_managed_entrypoint_generated.go")

	templateContent, err := os.ReadFile(templatePath)
	if err != nil {
		fail(err)
	}

	source := bytes.Buffer{}
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	source.WriteString("package manifest\n\n")
	source.WriteString("const managedEntrypointTemplate = ")
	source.WriteString(fmt.Sprintf("%q", string(templateContent)))
	source.WriteString("\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
