//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
)

func main() {
	cwd, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	skillRoot := filepath.Clean(filepath.Join(cwd, "../../../resources/skills/ctxpm"))
	outputPath := filepath.Join(cwd, "zz_bundled_docs_generated.go")

	paths := []string{}
	if err := filepath.WalkDir(skillRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(skillRoot, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		if relative == "cli/ctxpm" || relative == "cli/ctxpm.exe" {
			return nil
		}
		paths = append(paths, relative)
		return nil
	}); err != nil {
		fail(err)
	}
	sort.Strings(paths)

	source := bytes.Buffer{}
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	source.WriteString("package engine\n\n")
	source.WriteString("var bundledCtxpmSkillFiles = map[string]bundledCtxpmFile{\n")
	for _, relative := range paths {
		path := filepath.Join(skillRoot, filepath.FromSlash(relative))
		content, err := os.ReadFile(path)
		if err != nil {
			fail(err)
		}
		info, err := os.Stat(path)
		if err != nil {
			fail(err)
		}
		source.WriteString(fmt.Sprintf("%q: {Content: %q, Mode: 0o%o},\n", relative, string(content), info.Mode().Perm()))
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
