//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

func main() {
	cwd, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	skillPath := filepath.Clean(filepath.Join(cwd, "../../../resources/skills/ctxpm/SKILL.md"))
	yamlPath := filepath.Clean(filepath.Join(cwd, "../../../resources/skills/ctxpm/ctxpm-yaml.md"))
	outputPath := filepath.Join(cwd, "zz_bundled_docs_generated.go")

	skillContent, err := os.ReadFile(skillPath)
	if err != nil {
		fail(err)
	}
	yamlContent, err := os.ReadFile(yamlPath)
	if err != nil {
		fail(err)
	}

	source := bytes.Buffer{}
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	source.WriteString("package engine\n\n")
	source.WriteString("const bundledCtxpmSkillContent = ")
	source.WriteString(fmt.Sprintf("%q", string(skillContent)))
	source.WriteString("\n\nconst bundledCtxpmYAMLContent = ")
	source.WriteString(fmt.Sprintf("%q", string(yamlContent)))
	source.WriteString("\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
